blank_issues_enabled: false
issue_templates:
  - name: "âœ¨ Feature Request"
    about: Suggest an idea for improving Women Dev SG's website
    title: "[Feature Request]: "
    labels: enhancement
    assignees: ""
    url: .github/ISSUE_TEMPLATE/âœ¨-feature-request.md
  - name: ğŸ Bug report"
    about: Report a bug or unexpected behavior in Women Dev SG's website
    title: "[BUG]: "
    labels: bug
    assignees: ""
    url: .github/ISSUE_TEMPLATE/ğŸ-bug-report.md
  - name: ğŸ“ Documentation Improvement"
    about: Propose updates or improvements to the documentation/blog posts
    title: "[Docs]: "
    labels: documentation
    assignees: ""
    url: .github/ISSUE_TEMPLATE/ğŸ“-documentation-improvement.md
